WebAPI/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAPI.Models
{
    public class Employee
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter Employee Name")]
        public string EmployeeName { get; set; }

        [Required(ErrorMessage = "Please choose profile image")]
        public string EmployeeImage { get; set; }

        // Navigation Properties
        public int? DepartmentId { get; set; }
        public  Department Department { get; set; }
    }
}

WebAPI/ViewModels/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebAPI.Models;

namespace WebAPI.ViewModels
{
    public class EmployeeViewModel : EditImageViewModel
    {
        [Required(ErrorMessage = "Please enter Employee Name")]
        public string EmployeeName { get; set; }


        // Navigation Properties
        public int? DepartmentId { get; set; }
        public Department Department { get; set; }

    }
}

WebAPI/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAPI.Models;
using WebAPI.ViewModels;

namespace WebAPI.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class EmployeesController : Controller
    {
        private readonly EmployeeDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

     
        public EmployeesController(EmployeeDbContext context, IWebHostEnvironment hostEnvironment)
        {
             _context = context;
            webHostEnvironment = hostEnvironment;
        }

        // GET: Employees
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var employeeDbContext = _context.Employees.Include(e => e.Department);
            return View(await employeeDbContext.ToListAsync());
        }

        // GET: Employees/Details/5
     
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Department)
                .FirstOrDefaultAsync(m => m.Id == id);

            var EmployeeViewModel = new EmployeeViewModel()
            {
                Id = employee.Id,
                EmployeeName = employee.EmployeeName,
                DepartmentId = employee.DepartmentId,
                ExistingImage = employee.EmployeeImage
            };

            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create

        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "departmentName");
            return View();
        }

        // POST: Employees/Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeeName,EmployeeImage,DepartmentId")] EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {

                string uniqueFileName = ProcessUploadedFile(model);
                Employee employee = new Employee
                {
                    EmployeeName = model.EmployeeName,
                    DepartmentId = model.DepartmentId,
                    EmployeeImage = uniqueFileName
                };

                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "departmentName", model.DepartmentId);
            return View(model);
        }


        // GET: Employees/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id)        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);

            var EmployeeViewModel = new EmployeeViewModel()
            {
                Id = employee.Id,
                EmployeeName = employee.EmployeeName,
                DepartmentId = employee.DepartmentId,
                ExistingImage = employee.EmployeeImage
            };

            if (employee == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "departmentName", employee.DepartmentId);
            return View(EmployeeViewModel);
        }

        // POST: Employees/Edit/5
    //    [HttpPost, ActionName("Edit")]
      //  [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EmployeeName,EmployeeImage,DepartmentId")] EmployeeViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                var employee = await _context.Employees.FindAsync(model.Id);
                employee.EmployeeName = model.EmployeeName;
                employee.DepartmentId = model.DepartmentId;

                if (model.EmployeeProfile != null)
                {
                    if (model.ExistingImage != null)
                    {
                        string filePath = Path.Combine(webHostEnvironment.WebRootPath, "Uploads", model.ExistingImage);
                        System.IO.File.Delete(filePath);
                    }

                    employee.EmployeeImage = ProcessUploadedFile(model);
                }
                _context.Update(employee);
                await _context.SaveChangesAsync();

                //try
                //{
                //    _context.Update(model);
                //    await _context.SaveChangesAsync();
                //}
                //catch (DbUpdateConcurrencyException)
                //{
                //    if (!EmployeeExists(model.Id))
                //    {
                //        return NotFound();
                //    }
                //    else
                //    {
                //        throw;
                //    }
                //}
                return RedirectToAction(nameof(Index));
            }

      
        ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "departmentName", model.DepartmentId);
            return View();
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Department)
                .FirstOrDefaultAsync(m => m.Id == id);

            var EmployeeViewModel = new EmployeeViewModel()
            {
                Id = employee.Id,
                EmployeeName = employee.EmployeeName,
                DepartmentId = employee.DepartmentId,
                ExistingImage = employee.EmployeeImage
            };



            if (employee == null)
            {
                return NotFound();
            }

            return View(EmployeeViewModel);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            var CurrentImage = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", employee.EmployeeImage);
            _context.Employees.Remove(employee);
            
            if(await _context.SaveChangesAsync() > 0)
            {
                if (System.IO.File.Exists(CurrentImage))
                {
                    System.IO.File.Delete(CurrentImage);
                }
            }

            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }

        private string ProcessUploadedFile(EmployeeViewModel model)
        {
            string uniqueFileName = null;

            if (model.EmployeeProfile != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "Uploads");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.EmployeeProfile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.EmployeeProfile.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

WebAPI/Views/Employees/Create.cshtml
@model WebAPI.ViewModels.EmployeeViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmployeeName" class="control-label"></label>
                <input asp-for="EmployeeName" class="form-control" />
                <span asp-validation-for="EmployeeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeProfile" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="EmployeeProfile" class="custom-file-input" />
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <span asp-validation-for="EmployeeProfile" class="text-danger"></span>

                @*<label asp-for="EmployeeImage" class="control-label"></label>
            <input asp-for="EmployeeImage" class="form-control" />
            <span asp-validation-for="EmployeeImage" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-sm btn-primary rounded-0" />
                <a asp-action="Index" class="btn btn-sm btn-primary rounded-0">Back to List</a>

                @*<a asp-action="Index">Back to List</a>*@
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <script>
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAPI/Views/Employees/Delete.cshtml
@model WebAPI.ViewModels.EmployeeViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete </h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeProfile)
        </dt>
        <dd class="col-sm-10">
            <img src="~/Uploads/@Model.ExistingImage" class="img-thumbnail" height="100" width="100" asp-append-version="true" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department.departmentName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        @*<input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>*@
        <button type="submit" class="btn btn-sm btn-danger rounded-0"><i class="fa fa-trash-alt"></i> Delete</button>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-info rounded-0"><i class="fa fa-pencil-alt"></i> Edit</a>
        <a asp-action="Index" class="btn btn-sm btn-primary rounded-0"><i class="fas fa-fast-backward"></i> Back to List</a>
    </form>
</div>

WebAPI/Views/Employees/Details.cshtml
@model WebAPI.Models.Employee

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeImage)
        </dt>
        <dd class="col-sm-10">
            @*@Html.DisplayFor(model => model.EmployeeImage)*@
            <img src="~/Uploads/@Model.EmployeeImage" class="img-thumbnail" height="100" width="100" asp-append-version="true" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department.departmentName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-info rounded-0"><i class="fa fa-pencil-alt"></i> Edit</a>
    <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-sm btn-danger rounded-0"><i class="fa fa-trash-alt"></i> Delete</a>
    <a asp-action="Index" class="btn btn-sm btn-primary rounded-0"><i class="fas fa-fast-backward"></i> Back to List</a>

    @*<a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>*@
</div>

WebAPI/Views/Employees/Edit.cshtml
@model WebAPI.ViewModels.EmployeeViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="EmployeeName" class="control-label"></label>
                <input asp-for="EmployeeName" class="form-control" />
                <span asp-validation-for="EmployeeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeProfile" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="EmployeeProfile" class="custom-file-input" />
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <span asp-validation-for="EmployeeProfile" class="text-danger"></span>
                <img src="~/Uploads/@Model.ExistingImage" class="img-thumbnail" height="80" width="80" asp-append-version="true" />

                @*<label asp-for="EmployeeProfile" class="control-label"></label>
                    <input asp-for="EmployeeProfile" class="form-control" />
                    <span asp-validation-for="EmployeeProfile" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId"></select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <button type="submit" class="btn btn-sm btn-info rounded-0"><i class="fa fa-pencil-alt"></i> Update</button>
    <a asp-action="Index" class="btn btn-sm btn-primary rounded-0"><i class="fas fa-fast-backward"></i> Back to List</a>

    @*<a asp-action="Index">Back to List</a>*@
</div>

@section Scripts {
    <script>
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAPI/Views/Employees/Index.cshtml
@model IEnumerable<WebAPI.Models.Employee>

@{
    ViewData["Title"] = "Index";
}

<h2 class="text-center text-uppercase">list of Employees</h2>

<p>
    <a asp-action="Create" asp-controller="Employees" class="btn btn-primary rounded-0"><i class="fa fa-plus-circle"></i> Add New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>Action(s)</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeName)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">
                    <img src="~/Uploads/@item.EmployeeImage" class="img-thumbnail" height="100" width="100" asp-append-version="true" />
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department.departmentName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>